// @flow

export type typeEthBlock = {
  jsonrpc: string,
  id: 1,
  result: {
    difficulty: string,
    extraData: string,
    gasLimit: string,
    gasUsed: string,
    hash: string,
    logsBloom: string,
    miner: string,
    mixHash: string,
    nonce: string,
    number: string,
    parentHash: string,
    receiptsRoot: string,
    sha3Uncles: string,
    size: string,
    stateRoot: string,
    timestamp: string,
    totalDifficulty: string,
    transactions: [
      {
        blockHash: string,
        blockNumber: string,
        from: string,
        gas: string,
        gasPrice: string,
        hash: string,
        input: string,
        nonce: string,
        to: string,
        transactionIndex: string,
        value: string,
        v: string,
        r: string,
        s: string,
      },
    ],
    transactionsRoot: string,
    uncles: [],
  },
}
